### ISSUE TITLE
pep8 -> pycodestyle

### ISSUE THREAD

**Issue by glennmatthews** [Robpol86/flake8-pydocstyle#7]
The `pep8` package has been renamed to `pycodestyle`. `import pep8` now fails:

```
 File ".tox/flake8/lib/python2.7/site-packages/flake8_pep257.py", line 12, in <module>
    import pep8
ImportError: No module named pep8
```

**Comment by Robpol86** [comment]
pep8 is still importable, the problem was I didn't have it in my install_requires and flake8 stopped including it in theirs.

Fixed in:
* https://github.com/Robpol86/flake8-pydocstyle/commit/ad3c995b6d01a75934fa42f1bca27667b9ab8bae
* https://github.com/Robpol86/flake8-pydocstyle/commit/53b9b46800ee21be0e73743eded5fc302a820e14
